version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - DEVICE_USERNAME=${DEVICE_USERNAME}
      - DEVICE_PASSWORD=${DEVICE_PASSWORD}
    volumes:
      - devices_config:/Users/Shared/devices.json

volumes:
  devices_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/Shared/devices.json